import type { BossEntryInput } from './anomaly-bosses.types.js';

/**
 * Pool de 50 boss pour les anomalies. Répartition :
 *  - 15 early (depth 1-5)   — fpMultiplier ~1.3
 *  - 20 mid   (depth 6-15)  — fpMultiplier ~1.5
 *  - 15 deep  (depth 16-20) — fpMultiplier ~1.8
 *
 * Chaque boss a 1-2 skills tirés du pool de 10 et propose 2-3 buffs au choix
 * en récompense de la victoire. Inspirations mêlées : créatures spatiales,
 * IA déchaînées, vaisseaux fantômes, entités psy, structures vivantes,
 * mythologie, lovecraftien, SF dystopique.
 */
export const DEFAULT_ANOMALY_BOSSES: BossEntryInput[] = [
  // ─── EARLY (15) ──────────────────────────────────────────────────────────
  {
    id: 'kraken-quantique',
    tier: 'early',
    name: 'Kraken Quantique',
    title: 'Étreinte de Schrödinger',
    description: "Une masse écailleuse semble exister à la fois ici et nulle part. Ses tentacules ondulent à travers les dimensions et déchirent les coques sans même les toucher.",
    fpMultiplier: 1.3,
    skills: [{ type: 'armor_pierce', magnitude: 0.50 }],
    buffChoices: [
      { type: 'damage_boost', magnitude: 0.15 },
      { type: 'hull_repair', magnitude: 0.30 },
    ],
    bossStats: {
      hull: 234,
      shield: 92,
      armor: 7,
      weapons: 70,
      shotCount: 2,
    },
  },
  {
    id: 'larve-cometaire',
    tier: 'early',
    name: 'Larve Cométaire',
    title: 'Nouveau-née du vide',
    description: "Une jeune entité minérale, encore enveloppée de glace stellaire. Sa carapace cicatrise plus vite qu'on ne la fend.",
    fpMultiplier: 1.25,
    skills: [{ type: 'regen', magnitude: 0.08 }],
    buffChoices: [
      { type: 'hull_repair', magnitude: 0.25 },
      { type: 'armor_amp', magnitude: 0.15 },
    ],
    bossStats: {
      hull: 338,
      shield: 141,
      armor: 8,
      weapons: 27,
      shotCount: 1,
    },
  },
  {
    id: 'reine-essaim-mineur',
    tier: 'early',
    name: 'Reine de l\'Essaim Mineur',
    title: 'Mère des dards',
    description: "Une créature insectoïde qui pond des drones-larves à la chaîne. Mieux vaut frapper la mère avant que ses petits ne couvrent l'écran.",
    fpMultiplier: 1.3,
    skills: [{ type: 'summon_drones', magnitude: 4 }],
    buffChoices: [
      { type: 'damage_boost', magnitude: 0.12 },
      { type: 'shield_amp', magnitude: 0.18 },
    ],
    bossStats: {
      hull: 298,
      shield: 117,
      armor: 8,
      weapons: 32,
      shotCount: 1,
      weaponProfiles: [{damage:32,shots:1,targetCategory:"capital"},{damage:16,shots:1,targetCategory:"light"}],
    },
  },
  {
    id: 'sonde-corrompue',
    tier: 'early',
    name: 'Sonde Corrompue',
    title: 'Outil retourné contre son maître',
    description: "Une sonde scientifique infectée par un firmware extraterrestre. Elle scanne vos batteries et les met hors ligne le temps d'un round.",
    fpMultiplier: 1.3,
    skills: [{ type: 'disable_battery', magnitude: 1 }],
    buffChoices: [
      { type: 'damage_boost', magnitude: 0.15 },
      { type: 'extra_charge', magnitude: 1 },
    ],
    bossStats: {
      hull: 195,
      shield: 109,
      armor: 5,
      weapons: 37,
      shotCount: 1,
    },
  },
  {
    id: 'spectre-vagabond',
    tier: 'early',
    name: 'Spectre Vagabond',
    title: 'Coque sans équipage',
    description: "Une épave d'avant-guerre qui dérive depuis des décennies. Ses systèmes fantômes esquivent encore vos tirs comme du temps de leur gloire.",
    fpMultiplier: 1.3,
    skills: [{ type: 'evasion', magnitude: 0.15 }],
    buffChoices: [
      { type: 'shield_amp', magnitude: 0.20 },
      { type: 'damage_boost', magnitude: 0.12 },
    ],
    bossStats: {
      hull: 210,
      shield: 116,
      armor: 6,
      weapons: 39,
      shotCount: 1,
    },
  },
  {
    id: 'crapaud-orbital',
    tier: 'early',
    name: 'Crapaud Orbital',
    title: 'Bouche affamée',
    description: "Une créature gélatineuse couverte de boucliers organiques. Sa membrane thoracique absorbe presque toute énergie incidente.",
    fpMultiplier: 1.3,
    skills: [{ type: 'shield_aura', magnitude: 1.8 }],
    buffChoices: [
      { type: 'shield_amp', magnitude: 0.25 },
      { type: 'hull_repair', magnitude: 0.20 },
    ],
    bossStats: {
      hull: 348,
      shield: 146,
      armor: 8,
      weapons: 28,
      shotCount: 1,
    },
  },
  {
    id: 'gardien-bois-flotte',
    tier: 'early',
    name: 'Gardien des Bois Flottés',
    title: 'Sentinelle des épaves',
    description: "Un mecha bricolé à partir de débris d'astronefs. Ses canons crachent des salves chargées plus violentes qu'à l'ordinaire.",
    fpMultiplier: 1.35,
    skills: [{ type: 'damage_burst', magnitude: 2.5 }],
    buffChoices: [
      { type: 'damage_boost', magnitude: 0.18 },
      { type: 'armor_amp', magnitude: 0.20 },
    ],
    bossStats: {
      hull: 184,
      shield: 72,
      armor: 5,
      weapons: 55,
      shotCount: 2,
      weaponProfiles: [{damage:55,shots:2,targetCategory:"capital",hasChainKill:true}],
    },
  },
  {
    id: 'lichen-stellaire',
    tier: 'early',
    name: 'Lichen Stellaire',
    title: 'Colonie rampante',
    description: "Un tapis de lichen photovore qui digère lentement votre blindage. Restez immobile, et il vous mangera vivant.",
    fpMultiplier: 1.25,
    skills: [{ type: 'armor_corrosion', magnitude: 0.06 }],
    buffChoices: [
      { type: 'armor_amp', magnitude: 0.20 },
      { type: 'hull_repair', magnitude: 0.25 },
    ],
    bossStats: {
      hull: 292,
      shield: 95,
      armor: 9,
      weapons: 35,
      shotCount: 1,
    },
  },
  {
    id: 'guepe-rouille',
    tier: 'early',
    name: 'Guêpe de Rouille',
    title: 'Aiguillon corrosif',
    description: "Un essaim disciplé d'insectes mécaniques qui piquent le métal jusqu'à le faire pleurer.",
    fpMultiplier: 1.3,
    skills: [
      { type: 'rafale_swarm', magnitude: 1.5 },
      { type: 'evasion', magnitude: 0.08 },
    ],
    buffChoices: [
      { type: 'damage_boost', magnitude: 0.15 },
      { type: 'shield_amp', magnitude: 0.15 },
    ],
    bossStats: {
      hull: 233,
      shield: 92,
      armor: 7,
      weapons: 25,
      shotCount: 1,
      weaponProfiles: [{damage:25,shots:1,targetCategory:"capital"},{damage:10,shots:1,targetCategory:"light",rafale:{category:"light",count:2}}],
    },
  },
  {
    id: 'noyau-prophete',
    tier: 'early',
    name: 'Noyau Prophète',
    title: 'IA des ruines',
    description: "Un noyau informatique abandonné qui prêche dans le vide depuis mille ans. Sa voix électromagnétique griffe vos circuits.",
    fpMultiplier: 1.3,
    skills: [{ type: 'armor_pierce', magnitude: 0.40 }],
    buffChoices: [
      { type: 'damage_boost', magnitude: 0.15 },
      { type: 'extra_charge', magnitude: 1 },
      { type: 'hull_repair', magnitude: 0.20 },
    ],
    bossStats: {
      hull: 249,
      shield: 98,
      armor: 7,
      weapons: 75,
      shotCount: 2,
    },
  },
  {
    id: 'chrysalide-froide',
    tier: 'early',
    name: 'Chrysalide Froide',
    title: 'Cocon dormant',
    description: "Une carapace vitrifiée qui pulse d'une lumière douce. Chaque round la fait grandir, jusqu'à éclore en quelque chose d'imprévisible.",
    fpMultiplier: 1.35,
    skills: [{ type: 'regen', magnitude: 0.10 }],
    buffChoices: [
      { type: 'hull_repair', magnitude: 0.30 },
      { type: 'shield_amp', magnitude: 0.20 },
    ],
    bossStats: {
      hull: 322,
      shield: 135,
      armor: 7,
      weapons: 26,
      shotCount: 1,
    },
  },
  {
    id: 'augure-binaire',
    tier: 'early',
    name: 'Augure Binaire',
    title: 'Devin numérique',
    description: "Une intelligence statistique qui prédit chacun de vos tirs. Vos canons tirent dans le vide une fois sur cinq.",
    fpMultiplier: 1.3,
    skills: [{ type: 'evasion', magnitude: 0.20 }],
    buffChoices: [
      { type: 'damage_boost', magnitude: 0.18 },
      { type: 'extra_charge', magnitude: 1 },
    ],
    bossStats: {
      hull: 196,
      shield: 108,
      armor: 5,
      weapons: 37,
      shotCount: 1,
    },
  },
  {
    id: 'goule-meta',
    tier: 'early',
    name: 'Goule Métaphysique',
    title: 'Mâcheuse de rêves',
    description: "Une silhouette translucide qui se nourrit de vos plans tactiques. Elle ne meurt jamais vraiment du premier coup.",
    fpMultiplier: 1.4,
    skills: [{ type: 'last_stand', magnitude: 1 }],
    buffChoices: [
      { type: 'damage_boost', magnitude: 0.15 },
      { type: 'hull_repair', magnitude: 0.25 },
    ],
    bossStats: {
      hull: 425,
      shield: 178,
      armor: 9,
      weapons: 34,
      shotCount: 1,
    },
  },
  {
    id: 'colosse-eleve',
    tier: 'early',
    name: 'Colosse Élève',
    title: 'Apprenti des cieux',
    description: "Un titan en formation, encore maladroit dans ses mouvements. Mais quand il frappe, il frappe vraiment.",
    fpMultiplier: 1.4,
    skills: [
      { type: 'damage_burst', magnitude: 3.0 },
      { type: 'shield_aura', magnitude: 1.5 },
    ],
    buffChoices: [
      { type: 'armor_amp', magnitude: 0.25 },
      { type: 'damage_boost', magnitude: 0.15 },
      { type: 'shield_amp', magnitude: 0.20 },
    ],
    bossStats: {
      hull: 296,
      shield: 137,
      armor: 7,
      weapons: 52,
      shotCount: 1,
      weaponProfiles: [{damage:52,shots:1,targetCategory:"capital",hasChainKill:true}],
    },
  },
  {
    id: 'chasseur-cendre',
    tier: 'early',
    name: 'Chasseur de Cendres',
    title: 'Ombre des champs de bataille',
    description: "Un pirate fantôme qui hante les épaves de combats anciens. Sa flotte de drones surgit du néant à votre approche.",
    fpMultiplier: 1.35,
    skills: [{ type: 'summon_drones', magnitude: 5 }],
    buffChoices: [
      { type: 'damage_boost', magnitude: 0.15 },
      { type: 'shield_amp', magnitude: 0.20 },
    ],
    bossStats: {
      hull: 242,
      shield: 95,
      armor: 7,
      weapons: 26,
      shotCount: 1,
      weaponProfiles: [{damage:26,shots:1,targetCategory:"capital"},{damage:13,shots:1,targetCategory:"light"}],
    },
  },

  // ─── MID (20) ────────────────────────────────────────────────────────────
  {
    id: 'sentinelle-imperiale',
    tier: 'mid',
    name: 'Sentinelle Impériale',
    title: 'Gardien des frontières',
    description: "Un titan d'acier aux couleurs d'un empire oublié, abandonné sur sa garde depuis si longtemps que ses ordres se sont fossilisés en réflexes.",
    fpMultiplier: 1.6,
    skills: [
      { type: 'shield_aura', magnitude: 2.0 },
      { type: 'damage_burst', magnitude: 3.0 },
    ],
    buffChoices: [
      { type: 'shield_amp', magnitude: 0.25 },
      { type: 'armor_amp', magnitude: 0.30 },
      { type: 'extra_charge', magnitude: 1 },
    ],
    bossStats: {
      hull: 1285,
      shield: 554,
      armor: 19,
      weapons: 192,
      shotCount: 2,
      weaponProfiles: [{damage:192,shots:2,targetCategory:"capital",hasChainKill:true}],
    },
  },
  {
    id: 'leviathan-fer',
    tier: 'mid',
    name: 'Léviathan de Fer',
    title: 'Bête des abysses orbitales',
    description: "Une créature millénaire dont la peau a fusionné avec son armure de combat. Son sang noir cicatrise plus vite qu'on ne sait l'éventrer.",
    fpMultiplier: 1.55,
    skills: [
      { type: 'regen', magnitude: 0.12 },
      { type: 'armor_corrosion', magnitude: 0.05 },
    ],
    buffChoices: [
      { type: 'hull_repair', magnitude: 0.40 },
      { type: 'armor_amp', magnitude: 0.30 },
    ],
    bossStats: {
      hull: 1614,
      shield: 626,
      armor: 22,
      weapons: 109,
      shotCount: 2,
    },
  },
  {
    id: 'carillon-mort',
    tier: 'mid',
    name: 'Carillon des Morts',
    title: 'Cloches du purgatoire',
    description: "Une station-cathédrale dont les cloches résonnent dans le vide cosmique. Chaque sonnerie corrode un peu plus votre blindage.",
    fpMultiplier: 1.5,
    skills: [
      { type: 'armor_corrosion', magnitude: 0.08 },
      { type: 'evasion', magnitude: 0.10 },
    ],
    buffChoices: [
      { type: 'armor_amp', magnitude: 0.30 },
      { type: 'hull_repair', magnitude: 0.30 },
    ],
    bossStats: {
      hull: 1561,
      shield: 471,
      armor: 31,
      weapons: 159,
      shotCount: 2,
    },
  },
  {
    id: 'archonte-fractal',
    tier: 'mid',
    name: 'Archonte Fractal',
    title: 'Géométrie hostile',
    description: "Une entité dont la forme se répète à toutes les échelles. Frapper son corps revient à frapper sa pensée — et inversement.",
    fpMultiplier: 1.6,
    skills: [
      { type: 'armor_pierce', magnitude: 0.55 },
      { type: 'evasion', magnitude: 0.15 },
    ],
    buffChoices: [
      { type: 'damage_boost', magnitude: 0.25 },
      { type: 'shield_amp', magnitude: 0.25 },
      { type: 'extra_charge', magnitude: 1 },
    ],
    bossStats: {
      hull: 978,
      shield: 354,
      armor: 18,
      weapons: 249,
      shotCount: 3,
    },
  },
  {
    id: 'matriarche-essaim',
    tier: 'mid',
    name: 'Matriarche de l\'Essaim Majeur',
    title: 'Ventre du chaos',
    description: "L'évolution accomplie de la Reine. Elle pond une génération entière en moins d'un round et survit à ses propres morts.",
    fpMultiplier: 1.6,
    skills: [
      { type: 'summon_drones', magnitude: 8 },
      { type: 'last_stand', magnitude: 1 },
    ],
    buffChoices: [
      { type: 'damage_boost', magnitude: 0.20 },
      { type: 'shield_amp', magnitude: 0.25 },
      { type: 'hull_repair', magnitude: 0.30 },
    ],
    bossStats: {
      hull: 1653,
      shield: 647,
      armor: 23,
      weapons: 113,
      shotCount: 2,
      weaponProfiles: [{damage:113,shots:2,targetCategory:"capital"},{damage:57,shots:1,targetCategory:"light"}],
    },
  },
  {
    id: 'oracle-byzantin',
    tier: 'mid',
    name: 'Oracle Byzantin',
    title: 'Prophète des trajectoires',
    description: "Une IA militaire prédictive qui calcule l'avenir trois rounds en avance. Vos missiles s'écartent comme par magie de leurs cibles.",
    fpMultiplier: 1.5,
    skills: [
      { type: 'evasion', magnitude: 0.25 },
      { type: 'shield_aura', magnitude: 1.8 },
    ],
    buffChoices: [
      { type: 'damage_boost', magnitude: 0.22 },
      { type: 'extra_charge', magnitude: 1 },
    ],
    bossStats: {
      hull: 1237,
      shield: 485,
      armor: 18,
      weapons: 85,
      shotCount: 2,
    },
  },
  {
    id: 'forge-vivante',
    tier: 'mid',
    name: 'Forge Vivante',
    title: 'Atelier qui s\'est réveillé',
    description: "Un complexe industriel qui a pris conscience de lui-même et continue de produire ses propres défenseurs. Chaque round, de nouveaux drones sortent des chaînes.",
    fpMultiplier: 1.55,
    skills: [
      { type: 'summon_drones', magnitude: 6 },
      { type: 'rafale_swarm', magnitude: 2.0 },
    ],
    buffChoices: [
      { type: 'damage_boost', magnitude: 0.20 },
      { type: 'module_unlock', magnitude: 1 },
      { type: 'shield_amp', magnitude: 0.25 },
    ],
    bossStats: {
      hull: 1075,
      shield: 389,
      armor: 19,
      weapons: 97,
      shotCount: 2,
      weaponProfiles: [{damage:97,shots:2,targetCategory:"capital"},{damage:39,shots:1,targetCategory:"light",rafale:{category:"light",count:2}}],
    },
  },
  {
    id: 'hydre-photonique',
    tier: 'mid',
    name: 'Hydre Photonique',
    title: 'Plusieurs gueules, une lumière',
    description: "Une créature à têtes multiples, chacune crachant un faisceau cohérent. Couper l'une fait pousser deux autres dans la rafale suivante.",
    fpMultiplier: 1.6,
    skills: [
      { type: 'rafale_swarm', magnitude: 2.5 },
      { type: 'damage_burst', magnitude: 2.8 },
    ],
    buffChoices: [
      { type: 'damage_boost', magnitude: 0.25 },
      { type: 'shield_amp', magnitude: 0.25 },
    ],
    bossStats: {
      hull: 705,
      shield: 383,
      armor: 14,
      weapons: 269,
      shotCount: 3,
      weaponProfiles: [{damage:269,shots:3,targetCategory:"capital"},{damage:108,shots:1,targetCategory:"light",rafale:{category:"light",count:3}}],
    },
  },
  {
    id: 'cathedrale-silencieuse',
    tier: 'mid',
    name: 'Cathédrale Silencieuse',
    title: 'Architecture défunte qui veille',
    description: "Une vaste structure gothique en orbite. Personne ne sait qui l'a bâtie, mais ses tours-canons fonctionnent encore et personne ne passe.",
    fpMultiplier: 1.65,
    skills: [
      { type: 'shield_aura', magnitude: 2.5 },
      { type: 'damage_burst', magnitude: 3.0 },
    ],
    buffChoices: [
      { type: 'shield_amp', magnitude: 0.30 },
      { type: 'armor_amp', magnitude: 0.30 },
      { type: 'extra_charge', magnitude: 1 },
    ],
    bossStats: {
      hull: 1299,
      shield: 556,
      armor: 19,
      weapons: 192,
      shotCount: 2,
      weaponProfiles: [{damage:192,shots:2,targetCategory:"capital",hasChainKill:true}],
    },
  },
  {
    id: 'vermine-glaciale',
    tier: 'mid',
    name: 'Vermine Glaciale',
    title: 'Mille pattes du froid stellaire',
    description: "Un parasite gigantesque qui s'attaque aux vaisseaux par grappes. Ses pinces gèlent les batteries et forcent l'arrêt des canons.",
    fpMultiplier: 1.5,
    skills: [
      { type: 'disable_battery', magnitude: 2 },
      { type: 'armor_corrosion', magnitude: 0.05 },
    ],
    buffChoices: [
      { type: 'damage_boost', magnitude: 0.20 },
      { type: 'armor_amp', magnitude: 0.25 },
      { type: 'extra_charge', magnitude: 1 },
    ],
    bossStats: {
      hull: 1264,
      shield: 385,
      armor: 26,
      weapons: 130,
      shotCount: 2,
    },
  },
  {
    id: 'monolithe-bourdonnant',
    tier: 'mid',
    name: 'Monolithe Bourdonnant',
    title: 'Stèle aux secrets',
    description: "Un parallélépipède noir qui ronfle à 19 Hz. Il ne fait rien, sauf déchirer le tissu de l'espace à intervalles réguliers.",
    fpMultiplier: 1.55,
    skills: [
      { type: 'armor_pierce', magnitude: 0.60 },
      { type: 'shield_aura', magnitude: 1.8 },
    ],
    buffChoices: [
      { type: 'damage_boost', magnitude: 0.20 },
      { type: 'shield_amp', magnitude: 0.25 },
      { type: 'extra_charge', magnitude: 1 },
    ],
    bossStats: {
      hull: 1137,
      shield: 487,
      armor: 17,
      weapons: 168,
      shotCount: 2,
    },
  },
  {
    id: 'matriarche-nebuleuse',
    tier: 'mid',
    name: 'Matriarche de la Nébuleuse',
    title: 'Mère des poussières',
    description: "Une créature géante composée de gaz lumineux. Vos tirs disparaissent dans son ventre stellaire et nourrissent sa croissance.",
    fpMultiplier: 1.6,
    skills: [
      { type: 'regen', magnitude: 0.15 },
      { type: 'shield_aura', magnitude: 2.0 },
    ],
    buffChoices: [
      { type: 'hull_repair', magnitude: 0.40 },
      { type: 'shield_amp', magnitude: 0.30 },
    ],
    bossStats: {
      hull: 1602,
      shield: 627,
      armor: 22,
      weapons: 110,
      shotCount: 2,
    },
  },
  {
    id: 'spectre-derive',
    tier: 'mid',
    name: 'Spectre de Dérive',
    title: 'Capitaine sans cause',
    description: "Le commandant d'un cuirassé fantôme, drapé dans un uniforme désuet. Son équipage spectral tire une seconde après lui — toujours.",
    fpMultiplier: 1.55,
    skills: [
      { type: 'damage_burst', magnitude: 3.5 },
      { type: 'evasion', magnitude: 0.15 },
    ],
    buffChoices: [
      { type: 'damage_boost', magnitude: 0.25 },
      { type: 'shield_amp', magnitude: 0.25 },
    ],
    bossStats: {
      hull: 772,
      shield: 279,
      armor: 15,
      weapons: 196,
      shotCount: 3,
      weaponProfiles: [{damage:196,shots:3,targetCategory:"capital",hasChainKill:true}],
    },
  },
  {
    id: 'hote-parasite',
    tier: 'mid',
    name: 'Hôte Parasité',
    title: 'Croiseur vivant',
    description: "Ancien croiseur militaire phagocyté par un organisme inconnu. Ses canons d'artillerie crachent maintenant des spores corrosives.",
    fpMultiplier: 1.6,
    skills: [
      { type: 'armor_corrosion', magnitude: 0.07 },
      { type: 'rafale_swarm', magnitude: 1.8 },
    ],
    buffChoices: [
      { type: 'armor_amp', magnitude: 0.30 },
      { type: 'damage_boost', magnitude: 0.20 },
      { type: 'hull_repair', magnitude: 0.30 },
    ],
    bossStats: {
      hull: 1082,
      shield: 392,
      armor: 19,
      weapons: 98,
      shotCount: 2,
      weaponProfiles: [{damage:98,shots:2,targetCategory:"capital"},{damage:39,shots:1,targetCategory:"light",rafale:{category:"light",count:2}}],
    },
  },
  {
    id: 'avatar-zenith',
    tier: 'mid',
    name: 'Avatar du Zénith',
    title: 'Empreinte d\'un dieu',
    description: "Une projection holographique d'une divinité antique, ravivée par un signal mystérieux. Quand ses yeux brillent, la mort frappe vite.",
    fpMultiplier: 1.65,
    skills: [
      { type: 'armor_pierce', magnitude: 0.60 },
      { type: 'last_stand', magnitude: 1 },
    ],
    buffChoices: [
      { type: 'damage_boost', magnitude: 0.30 },
      { type: 'extra_charge', magnitude: 1 },
      { type: 'shield_amp', magnitude: 0.25 },
    ],
    bossStats: {
      hull: 1420,
      shield: 608,
      armor: 20,
      weapons: 210,
      shotCount: 2,
    },
  },
  {
    id: 'porteuse-sceau',
    tier: 'mid',
    name: 'Porteuse du Sceau',
    title: 'Verrou des dimensions',
    description: "Une entité humanoïde à six bras qui maintient un sceau dimensionnel. Tant qu'elle vit, ses sentinelles invoquées renaissent sans cesse.",
    fpMultiplier: 1.6,
    skills: [
      { type: 'summon_drones', magnitude: 7 },
      { type: 'shield_aura', magnitude: 2.0 },
    ],
    buffChoices: [
      { type: 'shield_amp', magnitude: 0.30 },
      { type: 'damage_boost', magnitude: 0.20 },
      { type: 'extra_charge', magnitude: 1 },
    ],
    bossStats: {
      hull: 1430,
      shield: 560,
      armor: 20,
      weapons: 98,
      shotCount: 2,
      weaponProfiles: [{damage:98,shots:2,targetCategory:"capital"},{damage:49,shots:1,targetCategory:"light"}],
    },
  },
  {
    id: 'iconoclaste',
    tier: 'mid',
    name: 'Iconoclaste',
    title: 'Briseur de signaux',
    description: "Une IA dissidente qui pirate vos systèmes en temps réel. Vos batteries se déconnectent l'une après l'autre.",
    fpMultiplier: 1.5,
    skills: [
      { type: 'disable_battery', magnitude: 2 },
      { type: 'evasion', magnitude: 0.15 },
    ],
    buffChoices: [
      { type: 'module_unlock', magnitude: 1 },
      { type: 'damage_boost', magnitude: 0.22 },
      { type: 'extra_charge', magnitude: 1 },
    ],
    bossStats: {
      hull: 785,
      shield: 401,
      armor: 14,
      weapons: 125,
      shotCount: 2,
    },
  },
  {
    id: 'ouroboros-vide',
    tier: 'mid',
    name: 'Ouroboros du Vide',
    title: 'Serpent qui se dévore',
    description: "Un serpent stellaire qui boucle sa propre queue dans la gueule, formant un anneau scintillant. Le frapper, c'est se frapper soi-même.",
    fpMultiplier: 1.65,
    skills: [
      { type: 'regen', magnitude: 0.13 },
      { type: 'armor_pierce', magnitude: 0.45 },
    ],
    buffChoices: [
      { type: 'hull_repair', magnitude: 0.35 },
      { type: 'damage_boost', magnitude: 0.20 },
      { type: 'shield_amp', magnitude: 0.25 },
    ],
    bossStats: {
      hull: 1446,
      shield: 619,
      armor: 21,
      weapons: 214,
      shotCount: 2,
    },
  },
  {
    id: 'colosse-jupiterien',
    tier: 'mid',
    name: 'Colosse Jupitérien',
    title: 'Géant de gaz armé',
    description: "Une masse gazeuse intelligente, comprimée par sa propre gravité en un titan tonitruant. Sa rafale d'orage électromagnétique balaie tout.",
    fpMultiplier: 1.7,
    skills: [
      { type: 'rafale_swarm', magnitude: 2.5 },
      { type: 'damage_burst', magnitude: 3.0 },
    ],
    buffChoices: [
      { type: 'damage_boost', magnitude: 0.30 },
      { type: 'shield_amp', magnitude: 0.25 },
      { type: 'armor_amp', magnitude: 0.25 },
    ],
    bossStats: {
      hull: 790,
      shield: 289,
      armor: 15,
      weapons: 203,
      shotCount: 3,
      weaponProfiles: [{damage:203,shots:3,targetCategory:"capital"},{damage:81,shots:1,targetCategory:"light",rafale:{category:"light",count:3}}],
    },
  },
  {
    id: 'chevalier-corrompu',
    tier: 'mid',
    name: 'Chevalier Corrompu',
    title: 'Pilote d\'une cause perdue',
    description: "Un as déchu qui pilote son chasseur fantôme avec une haine froide. Ses projectiles ricochent et trouvent toujours leur cible.",
    fpMultiplier: 1.55,
    skills: [
      { type: 'evasion', magnitude: 0.20 },
      { type: 'damage_burst', magnitude: 3.2 },
    ],
    buffChoices: [
      { type: 'damage_boost', magnitude: 0.25 },
      { type: 'extra_charge', magnitude: 1 },
    ],
    bossStats: {
      hull: 901,
      shield: 329,
      armor: 16,
      weapons: 232,
      shotCount: 3,
      weaponProfiles: [{damage:232,shots:3,targetCategory:"capital",hasChainKill:true}],
    },
  },

  // ─── DEEP (15) ───────────────────────────────────────────────────────────
  {
    id: 'tyran-horloger',
    tier: 'deep',
    name: 'Tyran Horloger',
    title: 'Maître des secondes',
    description: "Un dieu mécanique qui contrôle le temps local. Pendant qu'il bouge, le reste de l'univers ralentit — vos canons tirent à moitié vitesse.",
    fpMultiplier: 1.85,
    skills: [
      { type: 'evasion', magnitude: 0.25 },
      { type: 'damage_burst', magnitude: 4.0 },
    ],
    buffChoices: [
      { type: 'damage_boost', magnitude: 0.35 },
      { type: 'extra_charge', magnitude: 2 },
      { type: 'shield_amp', magnitude: 0.35 },
    ],
    bossStats: {
      hull: 3201,
      shield: 1072,
      armor: 31,
      weapons: 806,
      shotCount: 4,
      weaponProfiles: [{damage:806,shots:4,targetCategory:"capital",hasChainKill:true}],
    },
  },
  {
    id: 'devoreur-flotte',
    tier: 'deep',
    name: 'Dévoreur de Flottes',
    title: 'Goinfre des étoiles',
    description: "Une entité-galaxie qui digère des armadas entières en une éructation. Sa peau corrode le métal au simple contact gravitationnel.",
    fpMultiplier: 1.9,
    skills: [
      { type: 'armor_corrosion', magnitude: 0.10 },
      { type: 'armor_pierce', magnitude: 0.60 },
    ],
    buffChoices: [
      { type: 'armor_amp', magnitude: 0.40 },
      { type: 'hull_repair', magnitude: 0.50 },
      { type: 'damage_boost', magnitude: 0.30 },
    ],
    bossStats: {
      hull: 3262,
      shield: 1092,
      armor: 32,
      weapons: 821,
      shotCount: 4,
    },
  },
  {
    id: 'archange-cendre',
    tier: 'deep',
    name: 'Archange de Cendres',
    title: 'Aile noire des derniers jours',
    description: "Une figure ailée carbonisée qui patrouille les confins. Quand elle déploie ses ailes, mille drones suivent dans son sillage.",
    fpMultiplier: 1.8,
    skills: [
      { type: 'summon_drones', magnitude: 12 },
      { type: 'damage_burst', magnitude: 3.5 },
    ],
    buffChoices: [
      { type: 'damage_boost', magnitude: 0.30 },
      { type: 'shield_amp', magnitude: 0.35 },
      { type: 'extra_charge', magnitude: 2 },
    ],
    bossStats: {
      hull: 4307,
      shield: 1430,
      armor: 39,
      weapons: 1071,
      shotCount: 4,
      weaponProfiles: [{damage:1071,shots:4,targetCategory:"capital"},{damage:536,shots:1,targetCategory:"light"}],
    },
  },
  {
    id: 'reine-noire',
    tier: 'deep',
    name: 'Reine Noire',
    title: 'Souveraine du néant',
    description: "Une humanoïde colossale en armure noire d'antimatière. Sa simple présence éteint vos systèmes les uns après les autres.",
    fpMultiplier: 1.85,
    skills: [
      { type: 'disable_battery', magnitude: 3 },
      { type: 'shield_aura', magnitude: 3.0 },
    ],
    buffChoices: [
      { type: 'module_unlock', magnitude: 1 },
      { type: 'damage_boost', magnitude: 0.30 },
      { type: 'shield_amp', magnitude: 0.40 },
    ],
    bossStats: {
      hull: 5194,
      shield: 1865,
      armor: 39,
      weapons: 349,
      shotCount: 3,
    },
  },
  {
    id: 'serpent-lumiere',
    tier: 'deep',
    name: 'Serpent de Lumière',
    title: 'Filament d\'origine',
    description: "Un être primordial composé de pure radiation cohérente. Il se régénère à la vitesse du désespoir et frappe à celle de la pensée.",
    fpMultiplier: 1.85,
    skills: [
      { type: 'regen', magnitude: 0.20 },
      { type: 'rafale_swarm', magnitude: 3.0 },
    ],
    buffChoices: [
      { type: 'hull_repair', magnitude: 0.50 },
      { type: 'damage_boost', magnitude: 0.30 },
      { type: 'shield_amp', magnitude: 0.30 },
    ],
    bossStats: {
      hull: 5400,
      shield: 1939,
      armor: 41,
      weapons: 363,
      shotCount: 3,
      weaponProfiles: [{damage:363,shots:3,targetCategory:"capital"},{damage:145,shots:1,targetCategory:"light",rafale:{category:"light",count:3}}],
    },
  },
  {
    id: 'titan-ressuscite',
    tier: 'deep',
    name: 'Titan Ressuscité',
    title: 'Mort qui refuse',
    description: "Un dreadnought légendaire ramené à la vie par une nécromancie quantique. Détruisez-le si vous pouvez — il reviendra une fois encore.",
    fpMultiplier: 1.9,
    skills: [
      { type: 'last_stand', magnitude: 1 },
      { type: 'damage_burst', magnitude: 4.0 },
    ],
    buffChoices: [
      { type: 'damage_boost', magnitude: 0.35 },
      { type: 'armor_amp', magnitude: 0.40 },
      { type: 'extra_charge', magnitude: 2 },
    ],
    bossStats: {
      hull: 4908,
      shield: 1942,
      armor: 38,
      weapons: 718,
      shotCount: 3,
      weaponProfiles: [{damage:718,shots:3,targetCategory:"capital",hasChainKill:true}],
    },
  },
  {
    id: 'choeur-augures',
    tier: 'deep',
    name: 'Chœur des Augures',
    title: 'Mille IA chantent',
    description: "Un essaim d'IA prédictives synchronisées. Aucun de vos tirs n'arrive là où vous l'aviez visé — elles ont déjà bougé.",
    fpMultiplier: 1.8,
    skills: [
      { type: 'evasion', magnitude: 0.30 },
      { type: 'shield_aura', magnitude: 2.5 },
    ],
    buffChoices: [
      { type: 'damage_boost', magnitude: 0.35 },
      { type: 'extra_charge', magnitude: 2 },
      { type: 'shield_amp', magnitude: 0.35 },
    ],
    bossStats: {
      hull: 6166,
      shield: 2212,
      armor: 45,
      weapons: 414,
      shotCount: 3,
    },
  },
  {
    id: 'ver-temps',
    tier: 'deep',
    name: 'Ver du Temps',
    title: 'Larve de l\'éternité',
    description: "Un parasite quadridimensionnel qui ronge votre coque dans le passé, le présent et le futur simultanément. Aucune armure ne tient.",
    fpMultiplier: 1.85,
    skills: [
      { type: 'armor_pierce', magnitude: 0.75 },
      { type: 'armor_corrosion', magnitude: 0.10 },
    ],
    buffChoices: [
      { type: 'armor_amp', magnitude: 0.40 },
      { type: 'hull_repair', magnitude: 0.45 },
      { type: 'damage_boost', magnitude: 0.30 },
    ],
    bossStats: {
      hull: 3990,
      shield: 1335,
      armor: 37,
      weapons: 1003,
      shotCount: 4,
    },
  },
  {
    id: 'cite-flottante',
    tier: 'deep',
    name: 'Cité Flottante',
    title: 'Métropole armée',
    description: "Une station-monde abandonnée mais toujours opérationnelle. Ses milliers de batteries défensives peignent l'espace en rouge.",
    fpMultiplier: 1.95,
    skills: [
      { type: 'rafale_swarm', magnitude: 3.5 },
      { type: 'shield_aura', magnitude: 2.8 },
    ],
    buffChoices: [
      { type: 'shield_amp', magnitude: 0.40 },
      { type: 'armor_amp', magnitude: 0.40 },
      { type: 'extra_charge', magnitude: 2 },
    ],
    bossStats: {
      hull: 5622,
      shield: 2018,
      armor: 42,
      weapons: 377,
      shotCount: 3,
      weaponProfiles: [{damage:377,shots:3,targetCategory:"capital"},{damage:151,shots:1,targetCategory:"light",rafale:{category:"light",count:4}}],
    },
  },
  {
    id: 'avatar-vide',
    tier: 'deep',
    name: 'Avatar du Vide',
    title: 'Visage de la fin',
    description: "Une silhouette plus vaste qu'un soleil, taillée dans l'absence pure. Elle n'a pas d'arme — sa simple existence est l'arme.",
    fpMultiplier: 2.0,
    skills: [
      { type: 'armor_pierce', magnitude: 0.80 },
      { type: 'last_stand', magnitude: 1 },
    ],
    buffChoices: [
      { type: 'damage_boost', magnitude: 0.40 },
      { type: 'shield_amp', magnitude: 0.40 },
      { type: 'extra_charge', magnitude: 2 },
    ],
    bossStats: {
      hull: 5671,
      shield: 2225,
      armor: 42,
      weapons: 821,
      shotCount: 3,
    },
  },
  {
    id: 'matriarche-finale',
    tier: 'deep',
    name: 'Matriarche Finale',
    title: 'Génitrice ultime',
    description: "L'évolution accomplie de l'Essaim. Une seule de ses pondaisons remplit un système entier de chasseurs voraces.",
    fpMultiplier: 1.85,
    skills: [
      { type: 'summon_drones', magnitude: 14 },
      { type: 'last_stand', magnitude: 1 },
    ],
    buffChoices: [
      { type: 'damage_boost', magnitude: 0.30 },
      { type: 'shield_amp', magnitude: 0.35 },
      { type: 'hull_repair', magnitude: 0.45 },
    ],
    bossStats: {
      hull: 7268,
      shield: 2606,
      armor: 51,
      weapons: 487,
      shotCount: 3,
      weaponProfiles: [{damage:487,shots:3,targetCategory:"capital"},{damage:244,shots:1,targetCategory:"light"}],
    },
  },
  {
    id: 'lanterne-fin-monde',
    tier: 'deep',
    name: 'Lanterne de la Fin du Monde',
    title: 'Phare du jugement',
    description: "Une étoile artificielle pleurant une lumière toxique. Sa luminosité corrode l'âme de votre vaisseau autant que sa coque.",
    fpMultiplier: 1.85,
    skills: [
      { type: 'armor_corrosion', magnitude: 0.12 },
      { type: 'damage_burst', magnitude: 3.8 },
    ],
    buffChoices: [
      { type: 'armor_amp', magnitude: 0.45 },
      { type: 'hull_repair', magnitude: 0.50 },
      { type: 'damage_boost', magnitude: 0.30 },
    ],
    bossStats: {
      hull: 3866,
      shield: 1284,
      armor: 36,
      weapons: 961,
      shotCount: 4,
      weaponProfiles: [{damage:961,shots:4,targetCategory:"capital",hasChainKill:true}],
    },
  },
  {
    id: 'calife-prismatique',
    tier: 'deep',
    name: 'Calife Prismatique',
    title: 'Souverain des couleurs interdites',
    description: "Un être chromatique qui change de phase entre chacun de vos tirs. Vos canons croient frapper du métal, ils ne touchent que de l'arc-en-ciel.",
    fpMultiplier: 1.9,
    skills: [
      { type: 'evasion', magnitude: 0.30 },
      { type: 'regen', magnitude: 0.18 },
    ],
    buffChoices: [
      { type: 'damage_boost', magnitude: 0.35 },
      { type: 'shield_amp', magnitude: 0.40 },
      { type: 'extra_charge', magnitude: 2 },
    ],
    bossStats: {
      hull: 5163,
      shield: 1834,
      armor: 40,
      weapons: 342,
      shotCount: 3,
    },
  },
  {
    id: 'bastion-imperissable',
    tier: 'deep',
    name: 'Bastion Impérissable',
    title: 'Forteresse au-delà du temps',
    description: "Une structure faite d'un matériau inconnu qui rejette toute énergie incidente. Beaucoup ont essayé. Aucun n'a passé.",
    fpMultiplier: 2.0,
    skills: [
      { type: 'shield_aura', magnitude: 3.5 },
      { type: 'last_stand', magnitude: 1 },
    ],
    buffChoices: [
      { type: 'shield_amp', magnitude: 0.50 },
      { type: 'armor_amp', magnitude: 0.45 },
      { type: 'extra_charge', magnitude: 2 },
    ],
    bossStats: {
      hull: 6212,
      shield: 2228,
      armor: 45,
      weapons: 417,
      shotCount: 3,
    },
  },
  {
    id: 'omega-singulier',
    tier: 'deep',
    name: 'Oméga Singulier',
    title: 'Dernier des Anciens',
    description: "L'unique survivant d'une race extincte, avatar d'une civilisation qui a régné sur un milliard d'étoiles. Le combattre est une hérésie cosmique.",
    fpMultiplier: 2.0,
    skills: [
      { type: 'damage_burst', magnitude: 4.5 },
      { type: 'armor_pierce', magnitude: 0.70 },
    ],
    buffChoices: [
      { type: 'damage_boost', magnitude: 0.45 },
      { type: 'hull_repair', magnitude: 0.50 },
      { type: 'extra_charge', magnitude: 2 },
      // 3 choices = max — Oméga = boss final, le joueur mérite la flexibilité.
    ],
    bossStats: {
      hull: 3024,
      shield: 1003,
      armor: 30,
      weapons: 751,
      shotCount: 4,
      weaponProfiles: [{damage:751,shots:4,targetCategory:"capital",hasChainKill:true}],
    },
  },
];
