import type { ModuleDefinitionInput } from './modules.types.js';

/**
 * Initial pool of 57 modules — 19 per hull (10 communs + 6 rares + 3 épiques).
 * Edited via the admin UI after deploy. Seed is the source of truth at
 * first install + on re-seed for new envs.
 *
 * Conventions :
 *   - id : kebab-case `<hull>-<short-name>`. Stable across versions.
 *   - description : 1-2 phrases flavor text + chiffre clé.
 *   - effect : typed by Zod (stat / conditional / active).
 */
export const DEFAULT_MODULES: ModuleDefinitionInput[] = [
  // ─── COMBAT (10C / 6R / 3E) ────────────────────────────────────────────
  // Communs
  { id: 'combat-armored-plating',     hullId: 'combat', rarity: 'common',
    name: 'Plaque blindée standard', description: 'Renforcement de la coque par plaque blindée légère. +5% hull.',
    effect: { type: 'stat', stat: 'hull', value: 0.05 } },
  { id: 'combat-power-converter',     hullId: 'combat', rarity: 'common',
    name: 'Convertisseur de puissance', description: 'Optimise la décharge des canons. +8% damage.',
    effect: { type: 'stat', stat: 'damage', value: 0.08 } },
  { id: 'combat-reinforced-shield',   hullId: 'combat', rarity: 'common',
    name: 'Bouclier renforcé', description: 'Capacité supplémentaire de bouclier réactif. +7% shield.',
    effect: { type: 'stat', stat: 'shield', value: 0.07 } },
  { id: 'combat-targeting-stabilizer', hullId: 'combat', rarity: 'common',
    name: 'Stabilisateur de visée', description: 'Améliore la précision des canons. +5% damage.',
    effect: { type: 'stat', stat: 'damage', value: 0.05 } },
  { id: 'combat-light-thruster',      hullId: 'combat', rarity: 'common',
    name: 'Réacteur léger', description: 'Manœuvres améliorées. +5% speed.',
    effect: { type: 'stat', stat: 'speed', value: 0.05 } },
  { id: 'combat-emergency-repair',    hullId: 'combat', rarity: 'common',
    name: 'Régulateur d\'urgence', description: 'Auto-réparation entre combats. +5% regen.',
    effect: { type: 'stat', stat: 'regen', value: 0.05 } },
  { id: 'combat-armored-holds',       hullId: 'combat', rarity: 'common',
    name: 'Soutes blindées', description: 'Capacité de cargaison protégée. +5% cargo.',
    effect: { type: 'stat', stat: 'cargo', value: 0.05 } },
  { id: 'combat-extra-armor',         hullId: 'combat', rarity: 'common',
    name: 'Plaques supplémentaires', description: 'Armure accrue contre les tirs ennemis. +8% armor.',
    effect: { type: 'stat', stat: 'armor', value: 0.08 } },
  { id: 'combat-reinforced-hull',     hullId: 'combat', rarity: 'common',
    name: 'Coque renforcée', description: 'Structure consolidée. +8% hull.',
    effect: { type: 'stat', stat: 'hull', value: 0.08 } },
  { id: 'combat-fuel-bypass',         hullId: 'combat', rarity: 'common',
    name: 'Bypass carburant', description: 'Optimisation du flux énergétique. +5% cargo + tracé carburant amélioré.',
    effect: { type: 'stat', stat: 'cargo', value: 0.05 } },

  // Rares
  { id: 'combat-opening-salvo',       hullId: 'combat', rarity: 'rare',
    name: 'Salve d\'ouverture', description: 'Concentration totale au premier round. +50% damage round 1.',
    effect: { type: 'conditional', trigger: 'first_round', effect: { stat: 'damage', value: 0.50 } } },
  { id: 'combat-survival-protocol',   hullId: 'combat', rarity: 'rare',
    name: 'Protocole de survie', description: 'Régénération boostée en situation critique. Sous 30% hull → +30% shield regen.',
    effect: { type: 'conditional', trigger: 'low_hull', threshold: 0.30, effect: { stat: 'regen', value: 0.30 } } },
  { id: 'combat-veteran-crew',        hullId: 'combat', rarity: 'rare',
    name: 'Équipage vétéran', description: 'Équipage expérimenté. +15% damage et +15% hull.',
    effect: { type: 'stat', stat: 'damage', value: 0.15 } },
  { id: 'combat-strategist',          hullId: 'combat', rarity: 'rare',
    name: 'Stratège', description: 'Tacticien embarqué. +1 charge épique au démarrage de la run.',
    effect: { type: 'stat', stat: 'epic_charges_max', value: 1 } },
  { id: 'combat-anti-debris',         hullId: 'combat', rarity: 'rare',
    name: 'Anti-débris', description: 'Filtres avancés contre les débris. +20% hull.',
    effect: { type: 'stat', stat: 'hull', value: 0.20 } },
  { id: 'combat-counter-attack',      hullId: 'combat', rarity: 'rare',
    name: 'Riposte', description: 'Bonus de damage si l\'ennemi est plus puissant. enemy_fp_above 1000 → +20% damage.',
    effect: { type: 'conditional', trigger: 'enemy_fp_above', threshold: 1000, effect: { stat: 'damage', value: 0.20 } } },

  // Épiques
  { id: 'combat-emergency-repair-epic', hullId: 'combat', rarity: 'epic',
    name: 'Réparation d\'urgence', description: '1 charge → +50% hull immédiat sur la flotte.',
    effect: { type: 'active', ability: 'repair', magnitude: 0.50 } },
  { id: 'combat-overcharge',          hullId: 'combat', rarity: 'epic',
    name: 'Surcharge tactique', description: '1 charge → +100% damage le combat suivant.',
    effect: { type: 'active', ability: 'overcharge', magnitude: 1.00 } },
  { id: 'combat-ablative-shield',     hullId: 'combat', rarity: 'epic',
    name: 'Bouclier ablatif', description: '1 charge → +200% shield le combat suivant.',
    effect: { type: 'active', ability: 'shield_burst', magnitude: 2.00 } },

  // ─── SCIENTIFIC (10C / 6R / 3E) ────────────────────────────────────────
  // Communs
  { id: 'sci-shield-modulator',       hullId: 'scientific', rarity: 'common',
    name: 'Modulateur de bouclier', description: 'Modulation fine du bouclier. +5% shield.',
    effect: { type: 'stat', stat: 'shield', value: 0.05 } },
  { id: 'sci-data-bank',              hullId: 'scientific', rarity: 'common',
    name: 'Banque de données', description: 'Stockage de données accru. +8% regen entre combats.',
    effect: { type: 'stat', stat: 'regen', value: 0.08 } },
  { id: 'sci-stealth-coating',        hullId: 'scientific', rarity: 'common',
    name: 'Revêtement furtif', description: 'Furtivité au premier engagement. +10% damage round 1.',
    effect: { type: 'conditional', trigger: 'first_round', effect: { stat: 'damage', value: 0.10 } } },
  { id: 'sci-research-array',         hullId: 'scientific', rarity: 'common',
    name: 'Réseau de recherche', description: 'Modules de recherche embarqués. +5% damage.',
    effect: { type: 'stat', stat: 'damage', value: 0.05 } },
  { id: 'sci-energy-shield',          hullId: 'scientific', rarity: 'common',
    name: 'Bouclier énergétique', description: 'Surcouche énergétique. +8% shield.',
    effect: { type: 'stat', stat: 'shield', value: 0.08 } },
  { id: 'sci-hull-regen',             hullId: 'scientific', rarity: 'common',
    name: 'Régénération de coque', description: 'Auto-réparation. +6% regen.',
    effect: { type: 'stat', stat: 'regen', value: 0.06 } },
  { id: 'sci-light-armor',            hullId: 'scientific', rarity: 'common',
    name: 'Armure légère', description: 'Plaques composites. +5% armor.',
    effect: { type: 'stat', stat: 'armor', value: 0.05 } },
  { id: 'sci-cargo-bay',              hullId: 'scientific', rarity: 'common',
    name: 'Soute scientifique', description: 'Compartiments échantillonnage. +5% cargo.',
    effect: { type: 'stat', stat: 'cargo', value: 0.05 } },
  { id: 'sci-precision-weapons',      hullId: 'scientific', rarity: 'common',
    name: 'Armes de précision', description: 'Calibres réduits, viseurs accrus. +7% damage.',
    effect: { type: 'stat', stat: 'damage', value: 0.07 } },
  { id: 'sci-extra-thrusters',        hullId: 'scientific', rarity: 'common',
    name: 'Propulseurs supplémentaires', description: 'Manœuvres plus vives. +5% speed.',
    effect: { type: 'stat', stat: 'speed', value: 0.05 } },

  // Rares
  { id: 'sci-deep-scan',              hullId: 'scientific', rarity: 'rare',
    name: 'Scan profond', description: 'Anticipation des dégâts. -25% damage entrant le 1er round (équivalent +25% shield round 1).',
    effect: { type: 'conditional', trigger: 'first_round', effect: { stat: 'shield', value: 0.25 } } },
  { id: 'sci-quantum-research',       hullId: 'scientific', rarity: 'rare',
    name: 'Recherche quantique', description: 'Bonus de stats généralisé. +20% hull.',
    effect: { type: 'stat', stat: 'hull', value: 0.20 } },
  { id: 'sci-energy-weapon',          hullId: 'scientific', rarity: 'rare',
    name: 'Arme à énergie', description: 'Canons à plasma avancés. +20% damage.',
    effect: { type: 'stat', stat: 'damage', value: 0.20 } },
  { id: 'sci-shield-overload',        hullId: 'scientific', rarity: 'rare',
    name: 'Surcharge de bouclier', description: 'Bouclier renforcé en situation critique. Sous 30% hull → +50% shield.',
    effect: { type: 'conditional', trigger: 'low_hull', threshold: 0.30, effect: { stat: 'shield', value: 0.50 } } },
  { id: 'sci-knowledge-bank',         hullId: 'scientific', rarity: 'rare',
    name: 'Banque de savoir', description: 'Tacticien embarqué. +1 charge épique au démarrage.',
    effect: { type: 'stat', stat: 'epic_charges_max', value: 1 } },
  { id: 'sci-precision-strike',       hullId: 'scientific', rarity: 'rare',
    name: 'Frappe chirurgicale', description: 'Bonus contre flotte massive. enemy_fp_above 1500 → +25% damage.',
    effect: { type: 'conditional', trigger: 'enemy_fp_above', threshold: 1500, effect: { stat: 'damage', value: 0.25 } } },

  // Épiques
  { id: 'sci-deep-scan-epic',         hullId: 'scientific', rarity: 'epic',
    name: 'Scan profond — épique', description: '1 charge → révèle les outcomes cachés du prochain event narratif.',
    effect: { type: 'active', ability: 'scan', magnitude: 1.00 } },
  { id: 'sci-time-dilation',          hullId: 'scientific', rarity: 'epic',
    name: 'Dilatation temporelle', description: '1 charge → +150% damage le combat suivant.',
    effect: { type: 'active', ability: 'damage_burst', magnitude: 1.50 } },
  { id: 'sci-knowledge-burst',        hullId: 'scientific', rarity: 'epic',
    name: 'Éclair de savoir', description: '1 charge → +30% hull immédiat.',
    effect: { type: 'active', ability: 'repair', magnitude: 0.30 } },

  // ─── INDUSTRIAL (10C / 6R / 3E) ────────────────────────────────────────
  // Communs
  { id: 'indus-cargo-bay',            hullId: 'industrial', rarity: 'common',
    name: 'Soute cargo', description: 'Capacité de cargaison étendue. +5% cargo.',
    effect: { type: 'stat', stat: 'cargo', value: 0.05 } },
  { id: 'indus-mining-laser',         hullId: 'industrial', rarity: 'common',
    name: 'Laser minier', description: 'Laser de minage reconverti en arme. +5% damage.',
    effect: { type: 'stat', stat: 'damage', value: 0.05 } },
  { id: 'indus-fuel-tanks',           hullId: 'industrial', rarity: 'common',
    name: 'Réservoirs étendus', description: 'Réserves de carburant accrues. +10% speed.',
    effect: { type: 'stat', stat: 'speed', value: 0.10 } },
  { id: 'indus-reinforced-hold',      hullId: 'industrial', rarity: 'common',
    name: 'Soute renforcée', description: 'Plaques de blindage de soute. +8% cargo.',
    effect: { type: 'stat', stat: 'cargo', value: 0.08 } },
  { id: 'indus-mining-drill',         hullId: 'industrial', rarity: 'common',
    name: 'Foreuse industrielle', description: 'Rotation accrue. +7% damage.',
    effect: { type: 'stat', stat: 'damage', value: 0.07 } },
  { id: 'indus-bulk-armor',           hullId: 'industrial', rarity: 'common',
    name: 'Armure massive', description: 'Plaques de blindage industriel. +8% armor.',
    effect: { type: 'stat', stat: 'armor', value: 0.08 } },
  { id: 'indus-thick-hull',           hullId: 'industrial', rarity: 'common',
    name: 'Coque épaisse', description: 'Coque renforcée pour conditions extrêmes. +6% hull.',
    effect: { type: 'stat', stat: 'hull', value: 0.06 } },
  { id: 'indus-shield-extender',      hullId: 'industrial', rarity: 'common',
    name: 'Extension de bouclier', description: 'Capacité bouclier industrielle. +5% shield.',
    effect: { type: 'stat', stat: 'shield', value: 0.05 } },
  { id: 'indus-repair-bay',           hullId: 'industrial', rarity: 'common',
    name: 'Baie de réparation', description: 'Auto-réparation entre combats. +6% regen.',
    effect: { type: 'stat', stat: 'regen', value: 0.06 } },
  { id: 'indus-balanced-systems',     hullId: 'industrial', rarity: 'common',
    name: 'Systèmes équilibrés', description: 'Optimisation globale. +5% hull et résistance accrue.',
    effect: { type: 'stat', stat: 'hull', value: 0.05 } },

  // Rares
  { id: 'indus-salvage-protocol',     hullId: 'industrial', rarity: 'rare',
    name: 'Protocole de récupération', description: 'Bonus loot vaisseaux. +20% hull.',
    effect: { type: 'stat', stat: 'hull', value: 0.20 } },
  { id: 'indus-bulk-loot',            hullId: 'industrial', rarity: 'rare',
    name: 'Cargaison massive', description: 'Cargo industriel massif. +25% cargo.',
    effect: { type: 'stat', stat: 'cargo', value: 0.25 } },
  { id: 'indus-fortress',             hullId: 'industrial', rarity: 'rare',
    name: 'Forteresse', description: 'Bouclier en situation critique. Sous 30% hull → +40% shield.',
    effect: { type: 'conditional', trigger: 'low_hull', threshold: 0.30, effect: { stat: 'shield', value: 0.40 } } },
  { id: 'indus-foreman',              hullId: 'industrial', rarity: 'rare',
    name: 'Chef de chantier', description: 'Coordinateur stratégique. +1 charge épique au démarrage.',
    effect: { type: 'stat', stat: 'epic_charges_max', value: 1 } },
  { id: 'indus-armored-defense',      hullId: 'industrial', rarity: 'rare',
    name: 'Défense blindée', description: 'Plaques additionnelles. +25% armor.',
    effect: { type: 'stat', stat: 'armor', value: 0.25 } },
  { id: 'indus-overdrive',            hullId: 'industrial', rarity: 'rare',
    name: 'Surrégime', description: 'Sortie d\'urgence en force. last_round → +30% damage.',
    effect: { type: 'conditional', trigger: 'last_round', effect: { stat: 'damage', value: 0.30 } } },

  // Épiques
  { id: 'indus-quantum-jump',         hullId: 'industrial', rarity: 'epic',
    name: 'Saut quantique', description: '1 charge → skip le prochain combat (sans loot ni pertes).',
    effect: { type: 'active', ability: 'skip', magnitude: 1.00 } },
  { id: 'indus-megastructure',        hullId: 'industrial', rarity: 'epic',
    name: 'Mégastructure', description: '1 charge → +75% hull immédiat.',
    effect: { type: 'active', ability: 'repair', magnitude: 0.75 } },
  { id: 'indus-resource-lure',        hullId: 'industrial', rarity: 'epic',
    name: 'Appât à ressources', description: '1 charge → +200% shield le combat suivant.',
    effect: { type: 'active', ability: 'shield_burst', magnitude: 2.00 } },
];

/**
 * Starter modules attribués à chaque flagship lors de la migration,
 * selon sa coque actuelle. Doivent exister dans DEFAULT_MODULES.
 */
export const STARTER_MODULES_BY_HULL: Record<string, string> = {
  combat:     'combat-armored-plating',
  scientific: 'sci-shield-modulator',
  industrial: 'indus-cargo-bay',
};
